function export_vensim_params(cfg, mats, outAll)
%EXPORT_VENSIM_PARAMS Creates a one-row-per-material CSV for Vensim parameter coupling.

outdir = fullfile(pwd, "outputs");
if ~exist(outdir, 'dir'); mkdir(outdir); end

rows = [];
for i = 1:numel(mats)
    s = outAll(i).summary;

    row = table( ...
        string(s.material_key), string(s.material_name), ...
        string(s.loading_mode), ...
        s.AADT_total_two_way, s.pct_HGV, s.lane_split_factor, s.ESAs_per_HV_used, ...
        cfg.traffic.growth, cfg.discount_rate, ...
        s.avg_det_good_CI_per_year, s.avg_det_poor_CI_per_year, ...
        s.mean_maint_interval_year, s.mean_minor_interval_year, s.mean_overlay_interval_year, ...
        s.cost_per_km_year_ngn, s.cost_per_km_year_gbp, ...
        s.co2_per_km_year_t, ...
        s.npv_cost_ngn, s.npv_cost_gbp, ...
        s.total_co2_t, s.service_life_years, ...
        s.n_minor, s.n_overlay, s.n_recon, ...
        'VariableNames', { ...
        'material_key','material_name', ...
        'loading_mode', ...
        'AADT_two_way','pct_HGV','lane_split_factor','ESAs_per_HV_used', ...
        'traffic_growth','discount_rate', ...
        'avg_det_good_CI_per_year','avg_det_poor_CI_per_year', ...
        'mean_maint_interval_year','mean_minor_interval_year','mean_overlay_interval_year', ...
        'cost_per_km_year_ngn','cost_per_km_year_gbp', ...
        'co2_per_km_year_t', ...
        'npv_cost_ngn','npv_cost_gbp', ...
        'total_co2_t','service_life_years', ...
        'n_minor','n_overlay','n_recon'});

    rows = [rows; row]; %#ok<AGROW>
end

writetable(rows, fullfile(outdir, "vensim_params.csv"));

cfg_json = jsonencode(cfg);
fid = fopen(fullfile(outdir, "config_used.json"), 'w');
fprintf(fid, "%s", cfg_json);
fclose(fid);

end
